version: '3.8' 

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ImRoot@2020
      POSTGRES_DB: findSpell
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    container_name: backend_container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://root:ImRoot@2020@postgres:5432/findSpell

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: frontend_container
    command: npm run dev --host
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
